package adminEventos;
//
//  Generated by StarUML(tm) Java Add-In

import DTOS.evento.EventoConsultableDTO;
import excepciones.NegocioException;
import java.util.List;
import objetosNegocio.Evento;

//
//  @ Project : Aulas
//  @ File Name : ControlAdminEventos.java
//  @ Date : 05/05/2024
//  @ Author : 
//
//




public class ControlAdminEventos {
    private Evento eventoBO;

    public ControlAdminEventos() {
        this.eventoBO=new Evento();
    }

    protected EventoConsultableDTO agregarEvento( EventoConsultableDTO evento) throws NegocioException{
        try{
            return this.eventoBO.agregarEvento(evento);
        }catch(NegocioException e){
            throw e;
        }
    }

    protected EventoConsultableDTO editarEvento(EventoConsultableDTO evento,List<String> camposModificados) throws NegocioException{
        try{
            return this.eventoBO.editarEvento(evento, camposModificados);
        }catch(NegocioException e){
            throw e;
        }
    }

    protected boolean eliminarEvento(EventoConsultableDTO evento) throws NegocioException{
        try {
            return this.eventoBO.eliminarEvento(evento);
        } catch (NegocioException e) {
            throw e;
        }
    }

    protected List<EventoConsultableDTO> obtenerEventos() throws NegocioException{
        try {
            return this.eventoBO.obtenerEventos();
        } catch (NegocioException e) {
            throw e;
        }
    }
    
    protected EventoConsultableDTO obtenerEvento(EventoConsultableDTO evento)throws NegocioException{
        try {
            return this.eventoBO.obtenerEvento(evento);
        } catch (NegocioException e) {
            throw e;
        }
    }
}
