package adminEventos;
//
//  Generated by StarUML(tm) Java Add-In

import DTOS.evento.EventoConsultableDTO;
import excepciones.NegocioException;
import java.util.Calendar;
import java.util.List;

//
//  @ Project : Aulas
//  @ File Name : IAdminEventos.java
//  @ Date : 05/05/2024
//  @ Author : 
//
//




public interface IAdminEventos {
    public EventoConsultableDTO agregarEvento(EventoConsultableDTO evento)throws NegocioException;

    public EventoConsultableDTO editarEvento(EventoConsultableDTO evento,List<String> camposModificados)throws NegocioException;

    public boolean eliminarEvento(EventoConsultableDTO evento)throws NegocioException;

    public List<EventoConsultableDTO> obtenerEventos()throws NegocioException;
    
    public List<EventoConsultableDTO> obtenerEventos(String tipoEvento)throws NegocioException;
    
    public List<EventoConsultableDTO> obtenerEventos(Calendar fechaFiltro)throws NegocioException;
    
    public List<EventoConsultableDTO> obtenerEventos(String tipoEvento, Calendar fechaFiltro)throws NegocioException;
    
    public EventoConsultableDTO obtenerEvento(EventoConsultableDTO evento)throws NegocioException;
}
